platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12

inputs:
- name: scdf-for-pcf-cli-plugin
- name: version

outputs:
- name: built-plugin

run:
  path: scdf-for-pcf-cli-plugin/ci/tasks/build.sh

params:
  BUILT_PLUGIN_OUTPUT: built-plugin
  CF_CLI_PLUGIN_INPUT: scdf-for-pcf-cli-plugin
  PLUGIN_NAME: spring-cloud-dataflow-for-pcf-cli-plugin
  VERSION_INPUT: version
